trigger:
  branches:
    include:
    - main
  paths:
    include:
    - generated-samples/**

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: dotnetVersion
    value: '9.x'

stages:
- stage: ValidateSamples
  displayName: 'Validate Code Samples'
  jobs:
  
  - job: DetectChanges
    displayName: 'Detect Changed Samples'
    steps:
    - checkout: self
      fetchDepth: 2
      
    - script: |
        # Get changed sample directories
        git diff --name-only origin/main HEAD | grep "^generated-samples/" | cut -d'/' -f1-3 | sort | uniq | while read dir; do [ -d "$dir" ] && echo "$dir"; done > changed_samples.txt || touch changed_samples.txt
        
        # Split by language
        grep "^generated-samples/csharp/" changed_samples.txt > changed_csharp.txt || touch changed_csharp.txt
        grep "^generated-samples/python/" changed_samples.txt > changed_python.txt || touch changed_python.txt
        
        echo "Changed C# samples:"
        cat changed_csharp.txt
        echo "Changed Python samples:"
        cat changed_python.txt
        
        # Set variables for conditional jobs
        echo "##vso[task.setvariable variable=hasCSharpChanges;isOutput=true]$([ -s changed_csharp.txt ] && echo 'true' || echo 'false')"
        echo "##vso[task.setvariable variable=hasPythonChanges;isOutput=true]$([ -s changed_python.txt ] && echo 'true' || echo 'false')"
        
      displayName: 'Detect changes'
      name: 'detectChanges'
      
    - publish: changed_csharp.txt
      artifact: ChangedCSharp
      
    - publish: changed_python.txt
      artifact: ChangedPython

  - job: ValidateCSharp
    displayName: 'Validate C# Samples'
    dependsOn: DetectChanges
    condition: eq(dependencies.DetectChanges.outputs['detectChanges.hasCSharpChanges'], 'true')
    steps:
    - checkout: self
    - task: UseDotNet@2
      inputs:
        version: $(dotnetVersion)
    - download: current
      artifact: ChangedCSharp
    - script: sudo apt-get update && sudo apt-get install -y jq
      displayName: 'Install jq'
    - script: |
        chmod +x scripts/*.sh
        ./scripts/validate-samples.sh csharp "$(Pipeline.Workspace)/ChangedCSharp/changed_csharp.txt"
      displayName: 'Validate C# samples'
    - publish: validation-*.log
      artifact: CSharpResults
      condition: always()

  - job: ValidatePython
    displayName: 'Validate Python Samples'
    dependsOn: DetectChanges
    condition: eq(dependencies.DetectChanges.outputs['detectChanges.hasPythonChanges'], 'true')
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'
    - download: current
      artifact: ChangedPython
    - script: sudo apt-get update && sudo apt-get install -y jq
      displayName: 'Install jq'
    - script: |
        chmod +x scripts/*.sh
        ./scripts/validate-samples.sh python "$(Pipeline.Workspace)/ChangedPython/changed_python.txt"
      displayName: 'Validate Python samples'
    - publish: validation-*.log
      artifact: PythonResults
      condition: always()